### ISSUE TITLE
Update時のusersとlast_edited_timeについても出力されないように変更する必要あり

### ISSUE THREAD

**Issue by ukishima** [ikisuke/wagumi-sbt#5]
https://github.com/ikisuke/wagumi-sbt/blob/36acc6e609353f4172d970f5f8a5dc39ef9539d5/src/lib/metadataUpdate.js#L163

https://github.com/ikisuke/wagumi-sbt/blob/36acc6e609353f4172d970f5f8a5dc39ef9539d5/src/lib/metadataUpdate.js#L181-L185

https://github.com/ikisuke/wagumi-sbt/blob/36acc6e609353f4172d970f5f8a5dc39ef9539d5/src/lib/metadataUpdate.js#L195

https://github.com/ikisuke/wagumi-sbt/blob/36acc6e609353f4172d970f5f8a5dc39ef9539d5/src/lib/metadataUpdate.js#L212-L216

**Comment by ikisuke** [comment]
issue立てありがとうございます
@ukishima 

https://github.com/ikisuke/wagumi-sbt/blob/36acc6e609353f4172d970f5f8a5dc39ef9539d5/src/lib/metadataUpdate.js#L72-L74

こちらユーザーごとのメタデータ追加時に、last_edited_timeとusersを削除するようにしております。
